// Loads the canonical rules-manifest.json. This is the SINGLE source of truth shared with the Rust
// surface (which reads the same file via include_str!).
//
// The data is imported from the generated module src/generated/manifest-data.ts (regenerated by
// `npm run gen` from ../../rules-manifest.json) rather than read at runtime via node:fs. This keeps
// the published package self-contained (no out-of-package file paths) and browser/CDN-safe.
import manifest from "./generated/manifest-data.js";
import type { ManifestData, ManifestRule } from "./types.js";

export const MANIFEST: ManifestData = manifest as ManifestData;

const byId = new Map<string, ManifestRule>(MANIFEST.rules.map((r) => [r.id, r]));

export function lookupRule(id: string): ManifestRule {
  const r = byId.get(id);
  if (!r) throw new Error(`jsonstat-validator: unknown rule id "${id}"`);
  return r;
}
