// Structural pass: REUSES (does not reimplement) the official JSON-stat 2.0 JSON Schema 2020-12
// definitions vendored in schemas/vendored/. Violations are normalized into the same Finding shape
// the semantic engine uses, with code STRUCTURAL_VIOLATION and the ajv keyword retained in `meta`.
//
// The schema data is imported from the generated module src/generated/schemas.ts (regenerated by
// `npm run gen` from ../../schemas/vendored/*.json) rather than read at runtime via node:fs. This
// keeps the published package self-contained and browser/CDN-safe.
import { dataset as datasetSchema, collection as collectionSchema, dimension as dimensionSchema, index as indexSchema } from "./generated/schemas.js";
import type { Finding } from "./types.js";
import { lookupRule } from "./manifest.js";

// ajv ships the 2020-12 dialect as a separate build; its bundled types resolve at this path.
// @ts-ignore - ajv/dist/2020.js declaration resolution varies across ajv versions
import Ajv2020 from "ajv/dist/2020.js";
import addFormats from "ajv-formats";

// The curated/bundled schemas (schemas/curated/bundled/*.json) write the `updated` date hyphen
// literally, so their patterns compile cleanly under the default Unicode-flag RegExp. (The vendored
// upstream originals use an invalid `\-` escape and need a `unicodeRegExp: false` workaround — kept
// only for the curated-equiv-vendored parity test, not the production structural pass.)
const ajv = new (Ajv2020 as any)({ allErrors: true, strict: false });
(addFormats as any)(ajv);

const compiled = {
  dataset: ajv.compile(datasetSchema),
  collection: ajv.compile(collectionSchema),
  dimension: ajv.compile(dimensionSchema),
  index: ajv.compile(indexSchema),
};

function pickValidator(doc: any): (data: any) => boolean {
  const cls = doc?.class;
  if (cls === "dataset") return compiled.dataset;
  if (cls === "collection") return compiled.collection;
  if (cls === "dimension") return compiled.dimension;
  return compiled.index; // general oneOf of all three classes
}

export function validateStructural(doc: any): { ok: boolean; findings: Finding[] } {
  const validate = pickValidator(doc);
  if (validate(doc)) return { ok: true, findings: [] };
  const r = lookupRule("STRUCT");
  const errs = (validate as any).errors ?? [];
  const findings: Finding[] = errs.map((e: any) => ({
    code: r.code,
    ruleId: r.id,
    severity: r.severity,
    specRef: r.specRef,
    path: e.instancePath || "/",
    message: e.message ?? "JSON Schema violation",
    meta: { keyword: e.keyword, schemaPath: e.schemaPath, params: e.params },
  }));
  return { ok: false, findings };
}
